export const countries =[
{ label: 'Argentina', value: 'ar' }, 
{ label: 'Brazil', value: 'br' },   
// { label: 'Bulgaria', value: 'bg' }, 
{ label: 'Canada', value: 'ca' },   
// { label: 'China', value: 'cn' },    
{ label: 'Colombia', value: 'co' }, 
{ label: 'Cuba', value: 'cu' },     
// { label: 'Czechia', value: 'cz' },  
// { label: 'Egypt', value: 'eg' },
// { label: 'France', value: 'fr' },
// { label: 'Germany', value: 'de' },
// { label: 'Greece', value: 'gr' },
// { label: 'Hong Kong', value: 'hk' },
// { label: 'Hungary', value: 'hu' },
// { label: 'India', value: 'in' },
// { label: 'Indonesia', value: 'id' },
// { label: 'Ireland', value: 'ie' },
// { label: 'Israel', value: 'il' },
// { label: 'Italy', value: 'it' },
// { label: 'Japan', value: 'jp' },
// { label: 'Korea', value: 'kr' },
// { label: 'Latvia', value: 'lv' },
// { label: 'Lithuania', value: 'lt' },
// { label: 'Malaysia', value: 'my' },
{ label: 'Mexico', value: 'mx' },
// { label: 'Morocco', value: 'ma' },
// { label: 'Netherlands', value: 'nl' },
// { label: 'New Zealand', value: 'nz' },
// { label: 'Nigeria', value: 'ng' },
// { label: 'Norway', value: 'no' },
// { label: 'Philippines', value: 'ph' },
// { label: 'Poland', value: 'pl' },
// { label: 'Portugal', value: 'pt' },
// { label: 'Romania', value: 'ro' },
// { label: 'Russian Federation', value: 'ru' },
// { label: 'Saudi Arabia', value: 'sa' },
// { label: 'Serbia', value: 'rs' },
// { label: 'Singapore', value: 'sg' },
// { label: 'Slovakia', value: 'sk' },
// { label: 'Slovenia', value: 'si' },
// { label: 'South Africa', value: 'za' },
// { label: 'Sweden', value: 'se' },
// { label: 'Switzerland', value: 'ch' },
// { label: 'Taiwan, Province of China', value: 'tw' },
// { label: 'Thailand', value: 'th' },
// { label: 'Turkey', value: 'tr' },
// { label: 'Ukraine', value: 'ua' },
// { label: 'United Arab Emirates', value: 'ae' },
// { label: 'United Kingdom',value: 'gb'},
{ label: 'United States of America', value: 'us' },
{ label: 'Venezuela', value: 've' }
]

export const CATEGORIAS = [
  { value: 'general', label: 'General'},
  { value: 'business', label: 'Negocios'},
  { value: 'entertainment', label: 'Entretenimiento'},
  { value: 'health', label: 'Salud'},
  { value: 'science', label: 'Ciencia'},
  { value: 'sports', label: 'Deportes'},
  { value: 'technology', label: 'Tecnología'},
]